export function renderPage() {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="${process.env.PUBLIC_BASE_PATH || '/wechat-agent/'}"><title>微信个人助手</title><style>body{font:16px system-ui;max-width:680px;margin:30px auto;padding:0 16px;color:#172033}button,input{font:16px;padding:9px;margin:4px 0}button{cursor:pointer}.card{border:1px solid #e2e8f0;border-radius:16px;padding:22px;margin:16px 0;box-shadow:0 8px 30px #18315312}.status{white-space:pre-wrap;color:#64748b;background:#f8fafc;padding:12px;border-radius:10px}.qr{max-width:320px;display:block;margin:15px auto}.verify{border-top:1px solid #e2e8f0;margin-top:20px;padding-top:20px}.code{white-space:pre-wrap;background:#fff7ed;border:2px solid #f97316;padding:18px;font-size:24px;font-weight:700;color:#9a3412}.chat{display:none}.log{min-height:100px;border:1px solid #e2e8f0;padding:10px}.error{color:#b42318}</style></head><body><h1>微信个人助手</h1><p>绑定并完成身份核验后，直接使用微信 Bot 对话。</p><section class="card"><h2>第一步：绑定微信 Bot</h2><button id="start">获取绑定二维码</button><div id="status" class="status">准备就绪</div><img id="botQr" class="qr" style="display:none"></section><section id="verify" class="card verify" style="display:none"><h2>第二步：核验微信身份</h2><p>扫描下方二维码添加联系人 <b>助手</b>，然后向助手发送页面显示的 6 位数字验证码。</p><img class="qr" src="assistant-qr.jpg?v=3" alt="助手二维码" onerror="this.style.display='none';document.getElementById('qrError').style.display='block'"><div id="qrError" class="error" style="display:none">助手二维码加载失败。</div><div id="hint" class="code">正在生成验证码…</div></section><section id="chat" class="card chat"><h2>已验证</h2><p>身份已核验。请直接回到微信向 Bot 发送消息。</p><div id="log" class="log"></div></section><script>
const $=id=>document.getElementById(id);let bindingTimer,verifyTimer,verifyId;
async function verify(user){if(!verifyId)return;const r=await fetch('api/profile-verifications/'+verifyId,{headers:{'x-user-id':user}});if(!r.ok)return;const x=await r.json();if(x.status==='verified'){$('hint').textContent='✓ 已核验昵称：'+(x.profile.nickname||'未知')+'\\nwxid：'+x.profile.wxid;$('chat').style.display='block';clearInterval(verifyTimer)}}
async function bound(user,b){if(verifyId)return;const r=await fetch('api/profile-verifications',{method:'POST',headers:{'x-user-id':user,'content-type':'application/json'},body:JSON.stringify({ilinkUserId:b.profile?.providerUserId||b.providerBotId})});const x=await r.json();if(!r.ok){$('hint').textContent='验证码生成失败：'+(x.error||r.status);return}verifyId=x.id;$('hint').textContent='请向微信“助手”发送下面 6 位数字：\\n\\n'+x.code;verifyTimer=setInterval(()=>verify(user),1000);verify(user)}
async function status(user,id){const r=await fetch('api/bindings/'+id,{headers:{'x-user-id':user}});const b=await r.json();if(!r.ok){$('status').textContent=b.error||'状态查询失败';return}$('status').textContent='状态：'+b.status;if(b.status==='bound'){$('verify').style.display='block';await bound(user,b);clearInterval(bindingTimer)}}
$('start').onclick=async()=>{clearInterval(bindingTimer);clearInterval(verifyTimer);verifyId=null;$('verify').style.display='none';$('chat').style.display='none';const user='browser-'+crypto.randomUUID();const r=await fetch('api/bindings',{method:'POST',headers:{'x-user-id':user},body:'{}'});const b=await r.json();if(!r.ok){$('status').textContent=b.error||'绑定失败';return}sessionStorage.setItem('wa-user',user);$('status').textContent='请扫码确认\\n状态：pending';const q=await fetch('api/qr?payload='+encodeURIComponent(b.qrPayload));if(q.ok){$('botQr').src=(await q.json()).dataUrl;$('botQr').style.display='block'}bindingTimer=setInterval(()=>status(user,b.id),2000)};
</script></body></html>`
}
